# Generated by Django 4.2.3 on 2023-07-14 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
                ('etat', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encadrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.BooleanField(default=False)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculte', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('etat', models.BooleanField(default=False)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.employe')),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.encadrant')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.employe')),
            ],
        ),
        migrations.CreateModel(
            name='GestionnaireServiceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.employe')),
            ],
        ),
        migrations.CreateModel(
            name='DevLogiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologies_utilisees', models.CharField(max_length=100)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('etat', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
