# Generated by Django 4.2.3 on 2023-07-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employe_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, default='nom présisée', max_length=200),
        ),
        migrations.AlterField(
            model_name='employe',
            name='adresse',
            field=models.CharField(blank=True, default='nom présisée', max_length=200),
        ),
    ]
