# Generated by Django 4.2.3 on 2023-07-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_client_adresse_alter_employe_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
