# Generated by Django 4.2.3 on 2023-07-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_client_adresse_alter_employe_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='employe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employe'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='encadrant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.encadrant'),
        ),
    ]
