# Generated by Django 4.2.3 on 2023-07-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_employe_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(default='not mentioned', max_length=200),
        ),
    ]
