# Generated by Django 4.2.3 on 2023-07-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_client_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='encadrant',
            field=models.CharField(default='xx', max_length=100),
        ),
    ]
