# Generated by Django 4.2.3 on 2023-07-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_reclamation_reponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='reponse',
            field=models.TextField(default='Pas encore de réponse', max_length=100),
        ),
    ]
