# Generated by Django 4.2.3 on 2023-07-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_reclamation_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasion', models.CharField(max_length=100)),
                ('depart', models.DateField()),
                ('fin', models.DateField()),
                ('reponse', models.TextField(default='Pas encore de réponse', max_length=100)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employe')),
            ],
        ),
    ]
