# Generated by Django 4.2.3 on 2023-07-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_rasion_conge_raison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='reponse',
            field=models.TextField(default='Pas encore de réponse', max_length=100),
        ),
    ]
