# Generated by Django 4.2.3 on 2023-07-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_conge_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('fichier', models.FileField(null=True, upload_to='codes/')),
                ('devlogiciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.devlogiciel')),
            ],
        ),
    ]
