# Generated by Django 4.2.3 on 2023-07-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_code_likes_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='tache',
            field=models.CharField(default='nonfait', max_length=100),
        ),
    ]
