# Generated by Django 4.2.3 on 2023-07-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_tache_tache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='tache',
            new_name='etat',
        ),
    ]
