# Generated by Django 4.2.3 on 2023-07-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_assuranceautomobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assuranceautomobile',
            name='couverture',
        ),
        migrations.AddField(
            model_name='assuranceautomobile',
            name='reponse',
            field=models.TextField(default='Pas encore pris en charge', max_length=100),
        ),
    ]
