# Generated by Django 4.2.3 on 2023-07-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_assuranceautomobile_couverture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuranceHabitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('superficie', models.IntegerField()),
                ('reponse', models.TextField(default='Pas encore pris en charge', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
    ]
