# Generated by Django 4.2.3 on 2023-07-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_assurancehabitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='etat',
        ),
    ]
