# Generated by Django 4.2.3 on 2023-07-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_stagiaire_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
