# Generated by Django 4.2.3 on 2023-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_client_user_alter_employe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.CharField(default='python', max_length=100),
        ),
    ]
