# Generated by Django 4.2.3 on 2023-08-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_code_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='image',
            field=models.ImageField(blank=True, default='static\x07ssets\\profilepics\\default.png', null=True, upload_to='static\x07ssets\\profilepics'),
        ),
    ]
