# Generated by Django 4.2.3 on 2023-08-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_employe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='image',
            field=models.ImageField(blank=True, default='profilepics\\default.png', null=True, upload_to='profilepics/'),
        ),
    ]
