# Generated by Django 4.2.3 on 2023-08-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_employe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, default='profilepics/default.png', null=True, upload_to='profilepics/'),
        ),
    ]
