# Generated by Django 4.2.3 on 2023-08-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employe',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
