# Generated by Django 4.2.3 on 2023-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nb_accepte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employe',
            name='nb_accepte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='display',
            field=models.IntegerField(default=0),
        ),
    ]
