# Generated by Django 4.2.3 on 2023-08-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_client_nb_accepte_employe_nb_accepte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
