# Generated by Django 4.2.3 on 2023-08-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_employe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, default='media/profilepics/default.png', null=True, upload_to='profilepics/'),
        ),
    ]
