# Generated by Django 4.2.3 on 2023-08-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, default='profilepics/default.png', null=True, upload_to='profilepics/'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='image',
            field=models.ImageField(blank=True, default='profilepics/default.png', null=True, upload_to='profilepics/'),
        ),
    ]
