# Generated by Django 4.2.3 on 2023-08-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_him',
            field=models.BooleanField(default=False),
        ),
    ]
